swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Signup Successfully

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch user profile
      responses:
        "200":
          description: User profile successfully retrieved
          schema:
            $ref: "#/definitions/ApiResponse"
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update user profile
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      responses:
        "200":
          description: User profile updated successfully

  /account/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Fetch user accounts
      description: Retrieve all accounts for a specific user
      parameters:
        - in: path
          name: userId
          required: true
          type: string
          description: ID of the user
      responses:
        "200":
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"
        "404":
          description: User not found

  /transactions/{accountId}:
    get:
      tags:
        - Transactions Module
      summary: Fetch transactions for an account
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: ID of the account
        - in: query
          name: month
          required: false
          type: string
          description: Filter transactions by month (e.g., "2024-06")
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "404":
          description: Account not found

definitions:
  User:
    properties:
      email:
        type: string
      password:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string

  Login:
    properties:
      email:
        type: string
      password:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object

  Account:
    type: object
    properties:
      id:
        type: string
      balance:
        type: number
      title:
        type: string
        description: Account name

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
      category:
        type: string
      note:
        type: string
